extends: standard
plugins:
  - standard
  - promise
  - typescript
parser: typescript-eslint-parser
rules:
  "typescript/type-annotation-spacing":
    - error 
  no-unused-vars:
    - warn
  no-undef:
    - warn
