language: node_js
node_js:
  - "6"
script:
  - npm run lint
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/487fac2313701b836177
    on_success: change
    on_failure: always
    on_start: never